import{a as h,S as b,i as y}from"./assets/vendor-D0cagnvz.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))d(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const p of r.addedNodes)p.tagName==="LINK"&&p.rel==="modulepreload"&&d(p)}).observe(document,{childList:!0,subtree:!0});function o(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function d(t){if(t.ep)return;t.ep=!0;const r=o(t);fetch(t.href,r)}})();async function m(n,e){try{return(await h.get(`https://pixabay.com/api/?key=48639504-554e542bc8495b3a6c3499497&q=${n}&image_type=photo&orientation=horizontal&safesearch=true&page=${e}&per_page=15`)).data}catch(o){console.log(o)}}const i=document.querySelector(".gallery"),s=document.createElement("button"),l=document.querySelector(".loader");l.style.display="none";s.classList.add("loadButton");s.textContent="Load More";let f=new b(".gallery a",{captionsData:"alt",captionDelay:250});const u=document.querySelector(".form");let c=1,a="";u.addEventListener("submit",async n=>{n.preventDefault(),l.style.display="block",c=1;try{if(i.innerHTML="",s.style.display="none",a=u.inputText.value.trim(),u.inputText.value=a,!a||a===""){y.error({color:"#EF4040",message:"Error, input field is empty",messageColor:"#FAFAFB",maxWidth:"432",iconColor:"#FAFAFB"});return}const e=await m(a,c);if(e.hits.length===0){y.error({color:"#EF4040",message:"Sorry, there are no images matching your search query. Please, try again!",messageColor:"#FAFAFB",maxWidth:"432",iconColor:"#FAFAFB"});return}g(e.hits),s.style.display="block"}catch(e){console.error(e)}finally{l.style.display="none",document.body.append(s),f.refresh()}});s.addEventListener("click",async n=>{l.style.display="block",s.style.display="none";try{c++;const e=await m(a,c),o=i.children.length;if(g(e.hits),e.totalHits<=i.children.length){y.info({message:"We're sorry, but you've reached the end of search results."});return}const r=document.querySelectorAll(".image")[o].getBoundingClientRect();window.scrollBy({top:r.top-20,behavior:"smooth"}),s.style.display="block"}catch(e){console.error(e)}finally{l.style.display="none",f.refresh()}});function g(n){let e="";n.forEach(o=>{e+=`
      <li class="image">
        <a class="gallery-link" href="${o.largeImageURL}">
          <img src="${o.webformatURL}" alt="${o.tags}" class="gallery-image" width="360" height="200">
          <div class="imageStats">
          <p><span>Likes</span>${o.likes}</p>
          <p><span>Views</span> ${o.views}</p>
          <p><span>Comments</span> ${o.comments}</p>
          <p><span>Downloads</span> ${o.downloads}</p>
          </div>
          </a>
      </li>
    `}),i.insertAdjacentHTML("beforeend",e)}
//# sourceMappingURL=index.js.map
